FROM ubuntu:18.04

ARG BUILD_PACKAGES="build-essential cmake git libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-thread-dev libbz2-dev libmysql++-dev libssl-dev"
ARG RUNTIME_PACKAGES="libboost-program-options1.65.1 libboost-regex1.65.1 libboost-system1.65.1 libboost-thread1.65.1 libbz2-1.0 libmysql++3v5 libssl1.1"

RUN apt-get update -qqy && \
    apt-get install -qqy $BUILD_PACKAGES $RUNTIME_PACKAGES && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /mangos

WORKDIR /mangos

COPY . .

RUN mkdir -p /mangos/build/mangosd && \
    mkdir -p /mangos/run/mangosd

WORKDIR /mangos/build/mangosd
